laravel/composer.lock

Blocked by https://github.com/planetteamspeak/ts3phpframework/issues/184.
It's still not up2date as packagist is not up2date.

Update TS3PHPFramework dependency

---

laravel/app/Console/Commands/Instance/TeamspeakBot.php

Fixes the following exception: `Typed property App\Console\Commands\Instance\TeamspeakBot::$virtualserver must not be accessed before initialization`

Fix exception about uninitialized $virtualserver

---

laravel/app/Console/Commands/Process/CleanupDeadPids.php
laravel/app/Console/Kernel.php

The scheduling still takes care about the regular cleanup, but as administrator you will now also be able to execute the cleanup task manually using the Artisan command.
An additional check for the PID status has been added to ensure, that the existing PID is the expected PID and not any other, which randomly got the same PID.

Migrate dead PID cleanup cron to Artisan command

---

README.md
laravel/app/Console/Commands/Instance/TeamspeakBot.php

- Replace own signal handler with Laravel built-in
- Improve signal handling
Note: This change requires a new additional permission for the bot: `b_virtualserver_notify_unregister`
See https://laravel.com/docs/10.x/artisan#signal-handling for further information.

Improve signal handling for the bot

---

README.md
laravel/app/Http/Controllers/API/v1/BannerController.php
laravel/app/Http/Controllers/BannerConfigurationController.php
laravel/app/Http/Requests/BannerConfigurationUpsertRequest.php
laravel/app/Models/BannerTemplate.php
laravel/database/factories/BannerTemplateFactory.php
laravel/database/migrations/2023_08_17_012100_add_redirect_url_column_to_banner_templates.php
laravel/resources/views/banner/configuration.blade.php
laravel/routes/api.php

This change introduces a new API endpoint (URL) for each banner, which can be configured as "Hostbanner URL" in TeamSpeak.
In each banner configuration you can specify, if this should open the banner image, which the client can see at the moment or if the client should get redirected to any other URL.
You can for example create one banner with multiple templates and each template redirects to a different URL.

Add single "Hostbanner URL" for different redirects

---

laravel/app/Console/Commands/Instance/TeamspeakBot.php

When Redis is unreachable or any Redis action should fail, we will ignore this error and automatically retry it with the next iteration.

Extend Redis exception handling

---

laravel/resources/views/banner/template.blade.php

When you add and configure a template for a banner, you see it with the last saved information in the overview.
When you disabled it, an empty template was shown and you had to open its configuration in order to see, what is configured for it.
With this change, you will still see the preview with the last saved text, so that you don't have to open its configuration first.

Show rendered banner if only disabled

---

laravel/app/Http/Controllers/Helpers/DrawTextOnTemplateController.php

If you have text with line breaks or which need line breaks on your templates, you have to add each line to an extra configuration with new X-Y-Coordinates and font settings.
This change improves this by automatically wrapping too long text, which would not fit on the template without any line break. This is automatically done based on the font size, text length, X-Coordinate and template width.
Refs:
- https://www.php.net/manual/en/function.imagettfbbox.php
- https://www.php.net/manual/en/function.wordwrap.php

Automatically wrap too long text on templates

---

laravel/app/Http/Controllers/Helpers/BannerVariableController.php

Even with the highest refresh rate of the banner in TeamSpeak, the client always gets the current time minus a minute, although we already update the variable every 15 seconds. This change ensures, that the time is more accurate on the banner.

Fix incorrect time in banners

---

laravel/app/Http/Controllers/BannerConfigurationController.php

This is not necessary anymore since the changes in https://github.com/Sebbo94BY/teamspeak-dynamic-banner/commit/79e72cb5d559d43a80e945f2694a40ecd4a4e279.

Remove unnecessary if-condition

---

laravel/app/Http/Requests/BannerConfigurationUpsertRequest.php

The first definition should ensure, that it is an array with at least one element. The second definition should check the actual content of this element.
Closes #118.

Issue #118: Fix incorrect rule definition

---

laravel/database/factories/TemplateFactory.php

There was a dot between the actual filename and file extension missing.

Fix TemplateFactory file extension

---

laravel/database/migrations/2023_09_03_135919_create_fonts_table.php

Running `php artisan migrate` causes the following error:
```shell
INFO  Running migrations.  
2023_09_03_135919_create_fonts_table ................................................................................................... 51ms FAIL
In 2023_09_03_135919_create_fonts_table.php line 37:
rename(/var/www/laravel/public/fonts/universe-ce-45-light.ttf,/var/www/laravel/public/uploads/fonts/universe-ce-45-light.ttf): No such  
file or directory
```
This pull request fixes this issue.

Fix `No such file or directory` in `create_fonts_table` migration

---

laravel/database/migrations/2023_09_10_162338_change_serverquery_password_column_type_in_instances_table.php

Sometimes, the ServerQuery password couldn't be stored encrypted in the database as the column was too small. This change fixes this issue by changing the column type.

Fix `Data too long for column 'serverquery_password'`

---

laravel/.gitattributes

This application only runs on Linux, so we should force the End of Line to the Linux LF.
All currently committed files have already the LF, so there are no further actions required. Example:
```shell
$ file docker/scripts/prepare-docker-setup.sh
docker/scripts/prepare-docker-setup.sh: Bourne-Again shell script, ASCII text executable
```
```shell
$ git ls-files --eol docker/scripts/prepare-docker-setup.sh 
i/lf    w/lf    attr/                   docker/scripts/prepare-docker-setup.sh
```
Further information: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

Issue #148: Force LF EoL

---

laravel/resources/views/layouts/nav-main.blade.php

You can already set the `APP_NAME` in your `.env` file to give this application an individual name, which is also displayed in the browser tab.
Now it even gets displayed in the head navigation:

Show config app name instead of "Dynamic Banner"

---

docker/nginx/localhost.conf

This explicitly defines the maximum body size for HTTP requests. File uploads can reach this limit for example.

Docker: Specify `client_max_body_size`

---

laravel/app/Console/Commands/Banners/DisableBannerTemplate.php
laravel/app/Console/Commands/Banners/TimeBasedDisabling.php
laravel/app/Console/Commands/Banners/TimeBasedEnabling.php
laravel/app/Console/Kernel.php
laravel/app/Http/Controllers/BannerConfigurationController.php
laravel/app/Http/Requests/BannerConfigurationUpsertRequest.php
laravel/app/Models/BannerTemplate.php
laravel/database/migrations/2023_09_30_205434_add_time_based_columns_to_banner_templates_table.php
laravel/lang/de/views/banner/configuration.php
laravel/lang/en/views/banner/configuration.php
laravel/resources/views/banner/configuration.blade.php
laravel/tests/Feature/Commands/Banners/TimeBasedDisablingTest.php
laravel/tests/Feature/Commands/Banners/TimeBasedEnablingTest.php

Adds support for time-based configurations in order to configure banners to be visible only during specific time windows like between 8pm and 11pm.
Todo:
Closes #168

Add support for time-based configurations

---

Dockerfile
README.md
laravel/app/Http/Controllers/Helpers/DrawTextOnTemplateController.php
laravel/app/Http/Controllers/Helpers/SystemStatusController.php
laravel/app/Http/Requests/TemplateAddRequest.php
laravel/app/Http/Requests/TemplateUpdateRequest.php
laravel/app/Jobs/DrawGridSystemOnTemplate.php
laravel/database/factories/TemplateFactory.php
laravel/lang/de/views/inc/system/systemstatus.php
laravel/lang/de/views/modals/templates/modal-add.php
laravel/lang/de/views/modals/templates/modal-edit.php
laravel/lang/en/views/inc/system/systemstatus.php
laravel/lang/en/views/modals/templates/modal-add.php
laravel/lang/en/views/modals/templates/modal-edit.php
laravel/resources/views/inc/system/systemstatus.blade.php
laravel/resources/views/modals/templates/modal-add.blade.php
laravel/resources/views/modals/templates/modal-edit.blade.php
laravel/tests/Feature/API/v1/BannerTest.php

This pull request adds support for animated GIF images, so that you can use animated GIF based templates in your banner configurations.
Requirements / Setup Instructions:
1. Install https://ffmpeg.org/ on your Linux system (either via your operating systems package manager like `apt` or by following a installation documentation from their homepage)
2. Afterwards please ensure, that the path to the `ffmpeg` binary is part of the operating systems `PATH` environment variable, so that the following command succeeds on your command line: `ffmpeg -version`
3. Check the System Status page of your Dynamic Banner installation and check the status of `FFMpeg (GIF Support)` - it should be `Operational`
4. If everything went fine, you should now be able to upload a(n animated) GIF as template, which …

Add support for animated GIF images in banners

---

laravel/app/Http/Controllers/InstanceController.php

To avoid HTTP 500 errors and/or horrible exception traces, we will also catch here connection exceptions and rather print those in a specified area. This also ensures, that the page is accessible in case of unreachable TeamSpeak instances.

Catch TeamSpeak connection exceptions on instance page

---

laravel/app/Http/Controllers/BannerConfigurationController.php
laravel/app/Http/Kernel.php
laravel/app/Http/Middleware/AddTimezoneToHeaders.php
laravel/app/Http/Requests/ProfileUpdateRequest.php
laravel/app/Models/User.php
laravel/database/migrations/2023_10_07_134527_add_timezone_column_to_users_table.php
laravel/lang/de/views/instances.php
laravel/lang/de/views/profile/edit.php
laravel/lang/en/views/instances.php
laravel/lang/en/views/profile/edit.php
laravel/resources/views/administration/fonts.blade.php
laravel/resources/views/administration/users.blade.php
laravel/resources/views/banner/configuration.blade.php
laravel/resources/views/instances.blade.php
laravel/resources/views/layouts/footer-main.blade.php
laravel/resources/views/layouts/nav-main.blade.php
laravel/resources/views/profile/edit.blade.php
laravel/resources/views/templates.blade.php
laravel/tests/Feature/WebAuthRouteTest.php

The application automatically determines the clients timezone based on which preferred language the browser sends. This timezone is then automatically applied to the UI, so that it shows timestamps in the respective timezone.
If the timezone could not be determined by the application, it will fallback to the default application timezone, which is set in `config/app.php` (`timezone`).
On the profile page, the user can also enforce (set) a specific timezone:
Todo:
Closes #172

Add support for current timezone in UI

---

laravel/app/Http/Controllers/InstanceController.php

To avoid HTTP 500 errors and/or horrible exception traces, we will also catch here generic exceptions and rather print those in a specified area. This also ensures, that the page is accessible in case of unreachable TeamSpeak instances.

Catch generic exceptions on instance page

---

.github/workflows/coverage.yml
.github/workflows/phpcsfixer.yml
.github/workflows/phpunit.yml
README.md
docker-compose.yml
laravel/.gitignore
laravel/app/Console/Commands/Banners/TimeBasedDisabling.php
laravel/app/Console/Commands/Banners/TimeBasedEnabling.php
laravel/app/Http/Controllers/Helpers/SystemStatusController.php
laravel/app/Models/Banner.php
laravel/app/Models/BannerConfiguration.php
laravel/app/Models/BannerTemplate.php
laravel/app/Models/Font.php
laravel/app/Models/Instance.php
laravel/app/Models/InstanceProcess.php
laravel/app/Models/Localization.php
laravel/app/Models/Template.php
laravel/app/Models/TwitchApi.php
laravel/app/Models/TwitchStreamer.php
laravel/app/Models/User.php
laravel/composer.json
laravel/composer.lock
laravel/config/sanctum.php
laravel/phpunit.xml
laravel/tests/Feature/Commands/Banners/TimeBasedDisablingTest.php
laravel/tests/Feature/Commands/Banners/TimeBasedEnablingTest.php

- Upgrades Laravel from version 10.x to 11.x
- Upgrades all dependencies respectively
- Updates the README and application requirements as Laravel 11.x only supports PHP 8.2 and newer
- Migrates various configuration files to their new schemas / requirements
- Migrates Laravel `casts` from a property to a method
- Updates the GitHub actions to use the supported PHP versions 8.2 and newer

Upgrade Laravel to version 11.x
