Sebbo94BY/teamspeak-dynamic-banner

laravel/app/Console/Commands/Instance/TeamspeakBot.php

- Expire existing data before updating it
- Do not try to insert (update) empty data

Improve Redis update function

---

README.md

Adds a note for the required node version.
Otherwise you may see errors like this:
````shell
root@linux:/var/www/teamspeak-dynamic-banner/laravel# npm run build        
> build
> vite build
file:///var/www/teamspeak-dynamic-banner/laravel/node_modules/vite/bin/vite.js:7
await import('source-map-support').then((r) => r.default.install())
^^^^^
SyntaxError: Unexpected reserved word
at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code 1
npm ERR! path /var/www/teamspeak-dynamic-banner/laravel
npm ERR! command failed
npm ERR! command sh -c vite build
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-12T18_37_12_414Z-debug.log
````
````shell
0 verbose cli [ …
```

Add required node version to README

---

laravel/package-lock.json

Also fixes a vulnerability, found by NPM Audit.

Update NPM packages

---

laravel/composer.json
laravel/composer.lock

Reverts Sebi94nbg/teamspeak-dynamic-banner#20

Revert "[Composer]: Bump nunomaduro/collision from 6.4.0 to 7.1.0 in /laravel"

---

laravel/app/Http/Controllers/Helpers/BannerVariableController.php

See commit messages.
Solves #12

Issue #12: Fix bot disconnect exception

---

Dockerfile

This is helpful in the future for e. g. debugging issues / bugs or performance issues.

Add debugging packages to Docker

---

laravel/resources/views/instances.blade.php

- Show PID of each connected instance
- Show "connected since" of each connected instance
- Show the ServerQuery port

Add tooltips to instances view

---

laravel/app/Http/Controllers/Helpers/BannerVariableController.php

Renamed some variables to give them a proper name.

Optimize variable names

---

laravel/composer.lock

Includes the fix for not properly exiting loops after disconnects / connection losses and the very high CPU utilization, which was caused by the not ending loops.

Update the TS3PHPFramework library

---

laravel/app/Http/Controllers/API/v1/BannerController.php
laravel/app/Http/Controllers/BannerConfigurationController.php

These changes should better ensure that the banner images are not cached.

Improve cache control/handling for banner images

---

.github/workflows/coverage.yml
.github/workflows/phpunit.yml
docs/INSTALLATION.md
laravel/.env.testing
laravel/app/Http/Controllers/BannerVariableController.php
laravel/app/Models/BannerConfiguration.php
laravel/composer.json
laravel/phpunit.xml
laravel/tests/Feature/AdministrationRolesTest.php
laravel/tests/Feature/AdministrationUsersTest.php
laravel/tests/Feature/BannerTest.php
laravel/tests/Feature/BannerVariableTest.php
laravel/tests/Feature/Console/KernelTest.php
laravel/tests/Feature/InstanceTest.php
laravel/tests/Feature/Middleware/AuthenticateTest.php
laravel/tests/Feature/Middleware/RedirectIfAuthenticatedTest.php
laravel/tests/Feature/Setup/Installer/RequirementsTest.php
laravel/tests/Feature/TemplateTest.php

Improve PHPUnit configuration and workflows

---

laravel/app/Http/Controllers/Administration/FontsController.php
laravel/app/Http/Controllers/Administration/PhpInfoController.php
laravel/app/Http/Controllers/Administration/RolesController.php
laravel/app/Http/Controllers/Administration/SystemStatusController.php
laravel/app/Http/Controllers/Administration/UsersController.php
laravel/routes/web.php

Moves the page related functions to dedicated controllers.

Split AdministrationController

---

laravel/app/Console/Commands/Instance/TeamspeakBot.php
laravel/database/migrations/2023_08_19_001856_disable_new_banner_templates_by_default.php
laravel/resources/views/banner/configuration.blade.php
laravel/resources/views/banner/template.blade.php

Various quality improvements

---

laravel/app/Http/Controllers/API/v1/BannerController.php

Fixes the following error:
```shell
[2023-08-19 02:00:52] production.ERROR: Undefined array key 1 {"exception":"[object] (ErrorException(code: 0): Undefined array key 1 at /var/www/banner.local/laravel/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1732)
[stacktrace]
#0 /var/www/banner.local/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', '/var/www/banner...', 1732)
#1 /var/www/banner.local/laravel/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(1732): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Undefined array...', '/var/www/banner...', 1732)
#2 …
```

Fix `Undefined array key` in API BannerController

---

laravel/resources/sass/app.scss

Fixes the broken stylesheet for datatables.
Closes #81

Issue #81: Import missing Datatables CSS

---

laravel/app/Http/Controllers/Helpers/BannerVariableController.php

Add try-catch to avoid bot crashes when the TS3PHPFramework is unable to convert data.

Add `invalid parameter` exception handling

---

laravel/app/Http/Controllers/TemplateController.php
laravel/resources/views/administration/user/edit.blade.php
laravel/resources/views/administration/users.blade.php
laravel/resources/views/banner/add.blade.php
laravel/resources/views/banner/edit.blade.php
laravel/resources/views/banner/template_configuration.blade.php
laravel/resources/views/banners.blade.php
laravel/resources/views/dashboard.blade.php
laravel/resources/views/instance/edit.blade.php
laravel/resources/views/instances.blade.php
laravel/resources/views/layouts/app.blade.php
laravel/resources/views/template/edit.blade.php
laravel/resources/views/templates.blade.php

fix: dashboard.blade.php separate row for success message. Remove inline style. Cols now autowidth with 4 cards per row and a gap.
fix: add.blade.php add associate label tag
fix: edit.blade.php wrong closing tag
fix: templates.blade.php closing tag, delete duplicate content = value
fix: TemplateController.php variable from try not reachable in catch
fix: app.blade.php removed not allowed tags
fix: template_configuration.blade.php add associate label tag
fix: users.blade.php @elseif (($role != 'Super Admin') is already false because @if ($role == 'Super Admin')

few template fixes

---

laravel/app/Http/Controllers/TemplateController.php

Change redirect after adding/updating a template

---

laravel/app/Console/Commands/Banners/DisableBannerTemplate.php
laravel/app/Console/Kernel.php
laravel/app/Http/Controllers/BannerConfigurationController.php
laravel/app/Http/Requests/BannerConfigurationUpsertRequest.php
laravel/app/Models/BannerTemplate.php
laravel/database/migrations/2023_08_20_155448_add_disable_at_column_to_banner_templates.php
laravel/resources/views/banner/configuration.blade.php

This change introduces a new option for automatically disabling a banner template after a specific date and time.

Add option to automatically disable templates

---

laravel/app/Http/Controllers/Helpers/TeamSpeakVirtualserver.php

When the TeamSpeak bot is currently connected and you tried to edit the instance, you have most of the time seen a "HTTP 500 Server Error" page as the clients nickname was already in use by the bot. This change handles this error case and implements a better connection retry logic.

Fix/Improve error `nickname is already in use`

---

laravel/app/Console/Commands/Process/SendPcntlSignal.php
laravel/tests/Feature/Commands/Process/SendPcntlSignalTest.php

- Simplify the command a little bit
- Improve the command tests as they sometimes failed as the random "non-existing PID 1337" existed

Improve SendPcntlSignal command and tests

---

laravel/app/Console/Commands/Instance/TeamspeakBot.php
laravel/app/Http/Controllers/Helpers/SystemStatusController.php
laravel/app/Jobs/CloneOriginalTemplate.php
laravel/composer.json
laravel/database/migrations/2023_08_14_171638_create_permission_tables.php

here a few code optimizations.

few optimizations

---

laravel/app/Jobs/CloneOriginalTemplate.php

Issue #120: Fix incorrect property type

---

laravel/app/Http/Controllers/InstanceController.php

- The defined view does not exist at all
- Instead of returning a view, a redirect will be performed now
Closes #121.

Issue #121: Fix instance update function

---

docs/INSTALLATION.md
docs/UPDATE.md
laravel/package-lock.json
laravel/package.json

This pull request migrates the NPM dependencies from development to production.
It's recommend to do a clean NPM installation at your installation:
```shell
cd laravel/
rm -rf node_modules/ public/build/
npm install --omit=dev
npm run build
```

Migrate NPM dependencies and update documentations

---

laravel/app/Http/Controllers/InstanceController.php
laravel/app/Http/Requests/InstanceAddRequest.php
laravel/app/Http/Requests/InstanceUpdateRequest.php
laravel/resources/views/modals/instance/modal-add.blade.php
laravel/resources/views/modals/instance/modal-edit.blade.php

- Makes it more clear to end-users what will be used
- Simplyfies the respective controller code
- Fixes the issue, that RAW connections usually failed

Add checkbox for ServerQuery encryption

---

docs/INSTALLATION.md
docs/UPDATE.md
laravel/app/Http/Controllers/Helpers/SystemStatusController.php
laravel/app/Http/Controllers/InstanceController.php
laravel/lang/de/views/inc/system/systemstatus.php
laravel/lang/de/views/modals/instance/modal-add.php
laravel/lang/de/views/modals/instance/modal-edit.php
laravel/lang/en/views/inc/system/systemstatus.php
laravel/lang/en/views/modals/instance/modal-add.php
laravel/lang/en/views/modals/instance/modal-edit.php
laravel/resources/views/inc/system/systemstatus.blade.php
laravel/resources/views/modals/instance/modal-add.blade.php
laravel/resources/views/modals/instance/modal-edit.blade.php

Quality improvements

---

laravel/app/Console/Commands/Banners/EnableBannerTemplate.php
laravel/app/Console/Kernel.php
laravel/app/Http/Controllers/BannerConfigurationController.php
laravel/app/Http/Requests/BannerConfigurationUpsertRequest.php
laravel/app/Models/BannerTemplate.php
laravel/database/migrations/2023_10_21_133733_add_enable_at_column_to_banner_templates_table.php
laravel/lang/de/views/banner/configuration.php
laravel/lang/en/views/banner/configuration.php
laravel/resources/views/banner/configuration.blade.php
laravel/tests/Feature/Commands/Banners/EnableBannerTemplateTest.php

Add automatic enabling of banner template feature

---

laravel/app/Http/Controllers/Helpers/SystemStatusController.php
laravel/lang/de/views/inc/system/systemstatus.php
laravel/lang/en/views/inc/system/systemstatus.php

Check the individual commit messages.

Various Git System Status improvements

---

laravel/app/Http/Controllers/Administration/UsersController.php
laravel/app/Http/Kernel.php
laravel/composer.json
laravel/composer.lock
laravel/database/migrations/2023_08_14_171638_create_permission_tables.php

The migration file needs to be updated based on their upgrade guide. Effectively, the migration didn't change, but the classes and so on changed and thus, the file needs to be updated as it otherwise doesn't find the respective classes and properties anymore.
See https://github.com/spatie/laravel-permission/blob/main/docs/upgrading.md for further information.

Upgrade spatie/laravel-permission package

---

laravel/database/seeders/PermissionSeeder.php
laravel/database/seeders/RoleSeeder.php
laravel/resources/views/banner/template.blade.php

Adds additional permissions for the banner template stuff within a banner.

Add banner template permissions

---

laravel/app/Http/Controllers/Helpers/SystemStatusController.php
laravel/app/Http/Kernel.php
laravel/composer.lock
laravel/database/migrations/2023_08_14_171638_create_permission_tables.php

- Updates PHP CS Fixer to the latest version
- Applies respective code-style changes

Update PHP CS Fixer version
